### ISSUE TITLE
Use of LongPtr variables

### ISSUE THREAD

**Issue by mjl38** [OpenSourcePFCLibraries/2021#10]
I couldn't find any use the LongPtr variable type. I think we should implement that for window handles and wherever needed.  
Another thing is the exception of the Get- and SetWindowLongPtr (A/W) API. It's only defined for the 64 bit version of user32.dll.  We could define a function that calls either the longptr version or the long version of the APIs, according to the bitness of the running application. (maybe in the pfc_n_cst_app_manager or pfc_n_cst_platform objects, something like "of_SetWindowLong(...)".  
There's no rush, since right now everything is working for 64 bit compiled applications, mostly because we use either unsigned longs or LongLong variables.

**Comment by bruce-armstrong** [comment]
For what it's worth I went through the changes I made to the two apps I have running in 64 bit and the changes I made were (a) pretty much all Windows API calls (changing the value passed as the size of a structure) and (b) entirely within our own code, not in the PFC.

**Comment by mjl38** [comment]
Thank you Bruce, that explains :)  
What I'll do, if I have to do a 64 bit executable (which might be sooner than later), is implement any changes I need to do "on the go" to the PFC classes on my local PC's version. Maybe that's being very optimistic, time will tell. I don't think we'd have to do a release for every little change though. So this is going to take some time, unless other people start contributing too.
regards
