### ISSUE TITLE
Versions to be used in comments

### ISSUE THREAD

**Issue by mjl38** [OpenSourcePFCLibraries/2021#2]
Which version should we indicate in any comments? How do I know what version I'm working on?
For now I'm using "PB2021", but I don't think that's the best way of doing this.

**Comment by bruce-armstrong** [comment]
I'm not quite following.  There's a separate repository for the different versions.  This is the 2021 repository.

**Comment by mjl38** [comment]
I know, but I mean in the comments for changes in the powerbuilder code of the pfc classes themselves. There's headers with comments saying which version of the pfc you're running. Like '5' for example, which means very little to me.

**Comment by bruce-armstrong** [comment]
5 was the version of PowerBuilder when the PFC was first introduced.

**Comment by mjl38** [comment]
An example:
//////////////////////////////////////////////////////////////////////////////
//
//	Object Name:  pfc_w_master
//
//	Description:
//	The ancestor to all PFC window classes
//
//////////////////////////////////////////////////////////////////////////////
//	
//	Revision History
//
//	Version
//	5.0   Initial version
//	6.0   Added MRU and Logical Unit of Work service code
//
//////////////////////////////////////////////////////////////////////////////
//
/*
 * Open Source PowerBuilder Foundation Class Libraries
 *
 * Copyright (c) 2004-2017, All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted in accordance with the MIT License

 *
 * https://opensource.org/licenses/MIT
 *
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals and was originally based on software copyright (c) 
 * 1996-2004 Sybase, Inc. http://www.sybase.com.  For more
 * information on the Open Source PowerBuilder Foundation Class
 * Libraries see https://github.com/OpenSourcePFCLibraries
*/
//
//////////////////////////////////////////////////////////////////////////////

**Comment by mjl38** [comment]
So which version is to be used for pb2021?

**Comment by bruce-armstrong** [comment]
I'd suggest 2021.

**Comment by mjl38** [comment]
Seems like a plan to me! Thanks.
