### ISSUE TITLE
Longptr datatype and Handle() function

### ISSUE THREAD

**Issue by mjl38** [OpenSourcePFCLibraries/2021#9]
Not too long ago Appeon has updated the documentation / help to state correctly that the Handle() function returns a Longptr value: [Appeon ticket](https://www.appeon.com/standardsupport/search/view?id=7020). I see a lot of use of the function in the PFCs. We use Ulong for window handles (while the type of a windows handle is signed, I've been told) and also Long variables.
Thinking of 64 bit compilation, could we run into problems and should we change all of the types to longptr where appropiate.
I know this would be a hell of a job, so I'm going to ask for collaboration on the Q&A site of Appeon: [Q&A](https://community.appeon.com/index.php/qna/q-a/pfcs-not-using-longptr-variables-where-they-should)

**Comment by bruce-armstrong** [comment]
I can only find two places where PFC uses the Handle function.  One is in the platform service to determine the size of a text field and the other is in the treeview drag/drop service.  I see a lot of places in comments where the word "handle" is used, but it's not a use of that method.

I've got two PFC apps running in 64 bit mode and have not encountered any problems, but I'm not using those two services.  I did have to modify API calls, and I believe I already committed those changes to the PFC project.

**Comment by mjl38** [comment]
Aha, that would be great news then. I just did a search on "Handle" and saw that a lot (?) of times a handle is passed in to a function. I'll have a better look. Maybe also you haven't had any problems running 64 bit if the variable type used is Unsigned Long. (even though officially a pointer and handle is signed, I don't think you'll ever get a negative value in windows, so that might just save the day).

**Comment by mjl38** [comment]
After extensive advice on the Q&A site (see link above in the first post), I've decided not to change anything. Maybe I'll apply changes to my own local copy and when I have time to test it all, I might propose the changes here in the future.
I do think that more than the 2 places that Bruce mentions would have to change. Handles are being passed in functions in may places. This is what I found:
 ---------- Search: Searching Library D:\_GitHub\PB\2021-master\pfcwnsrv\pfcwnsrv.pbl for 'handle('    (11:56:59)
 ---------- 12 Matches Found On "handle(":
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_clientsize.0049:   of_ClientSize(Handle(iw_requestor), rl_Width, rl_Height)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_describe.0048:   of_describe(Handle(iw_requestor), rs_style[])
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_describe.0044:  of_describe(Handle(vw_describe), rs_style[])
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_style.0043:  of_style(Handle(vw_style), vul_style, vb_style)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_style.0046:   of_style(Handle(iw_requestor), vul_style, vb_style)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_style_extended.0047:   of_style_Extended(Handle(iw_requestor), vul_styleExtended, vb_styleExtended)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_style_extended.0044:  of_style_Extended(Handle(vw_styleExtended), vul_styleExtended, vb_styleExtended)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_clientsize.0046:   of_clientSize(Handle(vw_clientSize), rl_width, rl_height)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_isstyle_extended.0048:   lb_isStyleExtended = of_isStyle_Extended(Handle(vw_isStyleExtended), vul_StyleExtended)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_isstyle_extended.0051:   lb_isStyleExtended  = of_isStyle_Extended(Handle(iw_requestor), vul_styleExtended)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_isstyle.0049:   lb_isStyle     = of_isStyle(Handle(iw_requestor), vul_style)
NEEDS CHANGE: pfcwnsrv.pbl(pfc_n_cst_winsrv_style).of_isstyle.0047:   lb_isStyle    = of_isStyle(Handle(vw_isStyle), vul_Style)
 ---------- Done 12 Matches Found On "handle(":
 ---------- Finished Searching Library D:\_GitHub\PB\2021-master\pfcwnsrv\pfcwnsrv.pbl for 'handle('    (11:56:59)

 ---------- Search: Searching Library D:\_GitHub\PB\2021-master\pfcmain\pfcmain.pbl for 'handle('    (11:58:22)
 ---------- 2 Matches Found On "handle(":
NEEDS CHANGE: pfcmain.pbl(pfc_w_response)pfc_preopen.0046:   lul_hWnd      = Handle(this)
 ---------- Done 2 Matches Found On "handle(":
 ---------- Finished Searching Library D:\_GitHub\PB\2021-master\pfcmain\pfcmain.pbl for 'handle('    (11:58:22)

 ---------- Search: Searching Library D:\_GitHub\PB\2021-master\pfcapsrv\pfcapsrv.pbl for 'handle('    (11:58:52)
 ---------- 8 Matches Found On "handle(":
// What about the CloseHandle() API which also expects a handle parameter?: pfcapsrv.pbl(pfc_n_cst_filesrvunicode).of_setlastwritedatetime.0063:  CloseHandle(ll_handle)
// What about the CloseHandle() API which also expects a handle parameter?: pfcapsrv.pbl(pfc_n_cst_filesrvunicode).of_setcreationdatetime.0063:  CloseHandle(ll_handle)
// What about the CloseHandle() API which also expects a handle parameter?: pfcapsrv.pbl(pfc_n_cst_filesrvunicode).of_setlastaccessdate.0055:  CloseHandle(ll_handle)
NEEDS CHANGE: pfcapsrv.pbl(pfc_n_cst_platformunicode).of_GetTextSize.0070:   lul_Handle = Handle(lst_Temp)
// HAS NOTHING TO DO WITH HANDLE(): pfcapsrv.pbl(pfc_n_cst_tvsrv_levelsource)pfc_refreshlevel.0061:   ll_handle = this.of_GetHandle(lds_source, ll_row, ai_level)
// HAS NOTHING TO DO WITH HANDLE(): pfcapsrv.pbl(pfc_n_cst_tvsrv_levelsource).of_gethandle.0063:  Return of_GetHandle(ads_obj, al_row, li_level)
 ---------- Done 8 Matches Found On "handle(":
 ---------- Finished Searching Library D:\_GitHub\PB\2021-master\pfcapsrv\pfcapsrv.pbl for 'handle('    (11:58:52)

Cheers!
